### PR TITLE
Adding alternative instructions

### PR DESCRIPTION
**Pull request by denilsonsa**
I didn't want to install `poetry` just for this project that I intend to use only once. So I came up with a different set of instructions.

Also… In the end I haven't managed to run the project, because it requires `google-chrome`, which I don't have on my headless Raspberry Pi that doesn't even has X installed.

Also also… I'm not sure if it is Alternate or Alternative.

### CODE REVIEW

**Comment by mpupo** [comment]
Thanks for your PR. In addiction to your changes, I think that we will need a requirements file too.

**Comment by mpupo** [comment]
@denilsonsa can you allow edits from maintainers? I already wrote an commit to add to your PR and close everything. Here explains how to do it: https://docs.github.com/pt/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by denilsonsa** [comment]
It's already enabled: 
image

Se não funcionar, sinta-se à vontade para adicionar o commit depois do PR. ☺

**Comment by mpupo** [comment]
The needed changes are already done. So, I will close this PR right now.

Thanks @denilsonsa !

**Pull request merged**
